# Generated by Django 3.0 on 2022-08-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('worker', models.IntegerField()),
                ('started', models.DateField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
